# Form implementation generated from reading ui file '.\configurations_editor.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConfigurationsEditor(object):
    def setupUi(self, ConfigurationsEditor):
        ConfigurationsEditor.setObjectName("ConfigurationsEditor")
        ConfigurationsEditor.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(ConfigurationsEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_widget = QtWidgets.QTabWidget(parent=ConfigurationsEditor)
        self.tab_widget.setTabsClosable(True)
        self.tab_widget.setMovable(False)
        self.tab_widget.setObjectName("tab_widget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tab_widget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tab_widget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tab_widget)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ConfigurationsEditor)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ConfigurationsEditor)
        self.tab_widget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(ConfigurationsEditor.accept) # type: ignore
        self.buttonBox.rejected.connect(ConfigurationsEditor.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ConfigurationsEditor)

    def retranslateUi(self, ConfigurationsEditor):
        _translate = QtCore.QCoreApplication.translate
        ConfigurationsEditor.setWindowTitle(_translate("ConfigurationsEditor", "Edit device configurations..."))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab), _translate("ConfigurationsEditor", "Tab 1"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_2), _translate("ConfigurationsEditor", "Tab 2"))
