# Form implementation generated from reading ui file '.\orca_quest_config_editor.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OrcaQuestConfigEditor(object):
    def setupUi(self, OrcaQuestConfigEditor):
        OrcaQuestConfigEditor.setObjectName("OrcaQuestConfigEditor")
        OrcaQuestConfigEditor.resize(424, 549)
        self.horizontalLayout = QtWidgets.QHBoxLayout(OrcaQuestConfigEditor)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=OrcaQuestConfigEditor)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self._remote_server_combobox = RemoteServerComboBox(parent=OrcaQuestConfigEditor)
        self._remote_server_combobox.setObjectName("_remote_server_combobox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self._remote_server_combobox)
        self.label_2 = QtWidgets.QLabel(parent=OrcaQuestConfigEditor)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setContentsMargins(-1, 5, -1, -1)
        self.formLayout_3.setVerticalSpacing(6)
        self.formLayout_3.setObjectName("formLayout_3")
        self.xLabel = QtWidgets.QLabel(parent=OrcaQuestConfigEditor)
        self.xLabel.setObjectName("xLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.xLabel)
        self._left_spinbox = QtWidgets.QSpinBox(parent=OrcaQuestConfigEditor)
        self._left_spinbox.setObjectName("_left_spinbox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self._left_spinbox)
        self.widthLabel = QtWidgets.QLabel(parent=OrcaQuestConfigEditor)
        self.widthLabel.setObjectName("widthLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.widthLabel)
        self._right_spinbox = QtWidgets.QSpinBox(parent=OrcaQuestConfigEditor)
        self._right_spinbox.setObjectName("_right_spinbox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self._right_spinbox)
        self.yLabel = QtWidgets.QLabel(parent=OrcaQuestConfigEditor)
        self.yLabel.setObjectName("yLabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.yLabel)
        self._bottom_spinbox = QtWidgets.QSpinBox(parent=OrcaQuestConfigEditor)
        self._bottom_spinbox.setObjectName("_bottom_spinbox")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self._bottom_spinbox)
        self.heightLabel = QtWidgets.QLabel(parent=OrcaQuestConfigEditor)
        self.heightLabel.setObjectName("heightLabel")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.heightLabel)
        self._top_spinbox = QtWidgets.QSpinBox(parent=OrcaQuestConfigEditor)
        self._top_spinbox.setObjectName("_top_spinbox")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self._top_spinbox)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.formLayout_3)
        self.cameraNumberLabel = QtWidgets.QLabel(parent=OrcaQuestConfigEditor)
        self.cameraNumberLabel.setObjectName("cameraNumberLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.cameraNumberLabel)
        self._camera_number_spinbox = QtWidgets.QSpinBox(parent=OrcaQuestConfigEditor)
        self._camera_number_spinbox.setObjectName("_camera_number_spinbox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self._camera_number_spinbox)
        self.horizontalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(OrcaQuestConfigEditor)
        QtCore.QMetaObject.connectSlotsByName(OrcaQuestConfigEditor)

    def retranslateUi(self, OrcaQuestConfigEditor):
        _translate = QtCore.QCoreApplication.translate
        OrcaQuestConfigEditor.setWindowTitle(_translate("OrcaQuestConfigEditor", "Form"))
        self.label.setToolTip(_translate("OrcaQuestConfigEditor", "<html><head/><body><p>The name of the server that will actually instantiate the device.</p></body></html>"))
        self.label.setText(_translate("OrcaQuestConfigEditor", "Remote server"))
        self.label_2.setToolTip(_translate("OrcaQuestConfigEditor", "<html><head/><body><p>Rectangular region of interest to extract from the full sensor picture.</p></body></html>"))
        self.label_2.setText(_translate("OrcaQuestConfigEditor", "ROI"))
        self.xLabel.setText(_translate("OrcaQuestConfigEditor", "Left"))
        self.widthLabel.setText(_translate("OrcaQuestConfigEditor", "Right"))
        self.yLabel.setText(_translate("OrcaQuestConfigEditor", "Bottom"))
        self.heightLabel.setText(_translate("OrcaQuestConfigEditor", "Top"))
        self.cameraNumberLabel.setText(_translate("OrcaQuestConfigEditor", "Camera number"))
from remote_server_combobox import RemoteServerComboBox
