# Form implementation generated from reading ui file '.\editor.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CameraConfigurationEditor(object):
    def setupUi(self, CameraConfigurationEditor):
        CameraConfigurationEditor.setObjectName("CameraConfigurationEditor")
        CameraConfigurationEditor.resize(424, 549)
        self.horizontalLayout = QtWidgets.QHBoxLayout(CameraConfigurationEditor)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.form = QtWidgets.QFormLayout()
        self.form.setObjectName("form")
        self.label_2 = QtWidgets.QLabel(parent=CameraConfigurationEditor)
        self.label_2.setObjectName("label_2")
        self.form.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setContentsMargins(-1, 5, -1, -1)
        self.formLayout_3.setVerticalSpacing(6)
        self.formLayout_3.setObjectName("formLayout_3")
        self.xLabel = QtWidgets.QLabel(parent=CameraConfigurationEditor)
        self.xLabel.setObjectName("xLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.xLabel)
        self._left_spinbox = QtWidgets.QSpinBox(parent=CameraConfigurationEditor)
        self._left_spinbox.setObjectName("_left_spinbox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self._left_spinbox)
        self.widthLabel = QtWidgets.QLabel(parent=CameraConfigurationEditor)
        self.widthLabel.setObjectName("widthLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.widthLabel)
        self._right_spinbox = QtWidgets.QSpinBox(parent=CameraConfigurationEditor)
        self._right_spinbox.setObjectName("_right_spinbox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self._right_spinbox)
        self.yLabel = QtWidgets.QLabel(parent=CameraConfigurationEditor)
        self.yLabel.setObjectName("yLabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.yLabel)
        self._bottom_spinbox = QtWidgets.QSpinBox(parent=CameraConfigurationEditor)
        self._bottom_spinbox.setObjectName("_bottom_spinbox")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self._bottom_spinbox)
        self.heightLabel = QtWidgets.QLabel(parent=CameraConfigurationEditor)
        self.heightLabel.setObjectName("heightLabel")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.heightLabel)
        self._top_spinbox = QtWidgets.QSpinBox(parent=CameraConfigurationEditor)
        self._top_spinbox.setObjectName("_top_spinbox")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self._top_spinbox)
        self.form.setLayout(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.formLayout_3)
        self.horizontalLayout.addLayout(self.form)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(CameraConfigurationEditor)
        QtCore.QMetaObject.connectSlotsByName(CameraConfigurationEditor)

    def retranslateUi(self, CameraConfigurationEditor):
        _translate = QtCore.QCoreApplication.translate
        CameraConfigurationEditor.setWindowTitle(_translate("CameraConfigurationEditor", "Form"))
        self.label_2.setToolTip(_translate("CameraConfigurationEditor", "<html><head/><body><p>Rectangular region of interest to extract from the full sensor picture.</p></body></html>"))
        self.label_2.setText(_translate("CameraConfigurationEditor", "ROI"))
        self.xLabel.setText(_translate("CameraConfigurationEditor", "Left"))
        self.widthLabel.setText(_translate("CameraConfigurationEditor", "Right"))
        self.yLabel.setText(_translate("CameraConfigurationEditor", "Bottom"))
        self.heightLabel.setText(_translate("CameraConfigurationEditor", "Top"))
