# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import rpc_pb2 as rpc__pb2

GRPC_GENERATED_VERSION = "1.64.0"
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = "1.65.0"
SCHEDULED_RELEASE_DATE = "June 25, 2024"
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in rpc_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
        + f" This warning will become an error in {EXPECTED_ERROR_RELEASE},"
        + f" scheduled for release on {SCHEDULED_RELEASE_DATE}.",
        RuntimeWarning,
    )


class RemoteCallStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
            "/RemoteCall/Call",
            request_serializer=rpc__pb2.CallRequest.SerializeToString,
            response_deserializer=rpc__pb2.CallResponse.FromString,
            _registered_method=True,
        )
        self.DeleteReferent = channel.unary_unary(
            "/RemoteCall/DeleteReferent",
            request_serializer=rpc__pb2.DeleteReferentRequest.SerializeToString,
            response_deserializer=rpc__pb2.DeleteReferentResponse.FromString,
            _registered_method=True,
        )


class RemoteCallServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteReferent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RemoteCallServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Call": grpc.unary_unary_rpc_method_handler(
            servicer.Call,
            request_deserializer=rpc__pb2.CallRequest.FromString,
            response_serializer=rpc__pb2.CallResponse.SerializeToString,
        ),
        "DeleteReferent": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteReferent,
            request_deserializer=rpc__pb2.DeleteReferentRequest.FromString,
            response_serializer=rpc__pb2.DeleteReferentResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "RemoteCall", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("RemoteCall", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class RemoteCall(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Call(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/RemoteCall/Call",
            rpc__pb2.CallRequest.SerializeToString,
            rpc__pb2.CallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteReferent(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/RemoteCall/DeleteReferent",
            rpc__pb2.DeleteReferentRequest.SerializeToString,
            rpc__pb2.DeleteReferentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
