# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ShotViewerMainWindow(object):
    def setupUi(self, ShotViewerMainWindow):
        ShotViewerMainWindow.setObjectName("ShotViewerMainWindow")
        ShotViewerMainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=ShotViewerMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        ShotViewerMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ShotViewerMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu_add_view = QtWidgets.QMenu(parent=self.menubar)
        self.menu_add_view.setObjectName("menu_add_view")
        self.menuWorkspace = QtWidgets.QMenu(parent=self.menubar)
        self.menuWorkspace.setObjectName("menuWorkspace")
        ShotViewerMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ShotViewerMainWindow)
        self.statusbar.setObjectName("statusbar")
        ShotViewerMainWindow.setStatusBar(self.statusbar)
        self.action_save_workspace_as = QtGui.QAction(parent=ShotViewerMainWindow)
        self.action_save_workspace_as.setObjectName("action_save_workspace_as")
        self.action_load_workspace = QtGui.QAction(parent=ShotViewerMainWindow)
        self.action_load_workspace.setObjectName("action_load_workspace")
        self.menuWorkspace.addAction(self.action_save_workspace_as)
        self.menuWorkspace.addAction(self.action_load_workspace)
        self.menubar.addAction(self.menu_add_view.menuAction())
        self.menubar.addAction(self.menuWorkspace.menuAction())

        self.retranslateUi(ShotViewerMainWindow)
        QtCore.QMetaObject.connectSlotsByName(ShotViewerMainWindow)

    def retranslateUi(self, ShotViewerMainWindow):
        _translate = QtCore.QCoreApplication.translate
        ShotViewerMainWindow.setWindowTitle(_translate("ShotViewerMainWindow", "MainWindow"))
        self.menu_add_view.setTitle(_translate("ShotViewerMainWindow", "Add view"))
        self.menuWorkspace.setTitle(_translate("ShotViewerMainWindow", "Workspace"))
        self.action_save_workspace_as.setText(_translate("ShotViewerMainWindow", "Save as..."))
        self.action_load_workspace.setText(_translate("ShotViewerMainWindow", "Load..."))
