# Form implementation generated from reading ui file '.\add_constant_table.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddTableDialog(object):
    def setupUi(self, AddTableDialog):
        AddTableDialog.setObjectName("AddTableDialog")
        AddTableDialog.resize(400, 69)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddTableDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.deviceNameLabel = QtWidgets.QLabel(parent=AddTableDialog)
        self.deviceNameLabel.setObjectName("deviceNameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.deviceNameLabel)
        self.table_name_line_edit = QtWidgets.QLineEdit(parent=AddTableDialog)
        self.table_name_line_edit.setObjectName("table_name_line_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.table_name_line_edit)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AddTableDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AddTableDialog)
        self.buttonBox.accepted.connect(AddTableDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(AddTableDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddTableDialog)

    def retranslateUi(self, AddTableDialog):
        _translate = QtCore.QCoreApplication.translate
        AddTableDialog.setWindowTitle(_translate("AddTableDialog", "Add constant table..."))
        self.deviceNameLabel.setText(_translate("AddTableDialog", "Table name"))
