# Form implementation generated from reading ui file '.\constant_tables_editor.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConstantTablesEditor(object):
    def setupUi(self, ConstantTablesEditor):
        ConstantTablesEditor.setObjectName("ConstantTablesEditor")
        ConstantTablesEditor.resize(607, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(ConstantTablesEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_widget = QtWidgets.QTabWidget(parent=ConstantTablesEditor)
        self.tab_widget.setTabsClosable(True)
        self.tab_widget.setMovable(False)
        self.tab_widget.setObjectName("tab_widget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tab_widget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tab_widget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tab_widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_button = QtWidgets.QPushButton(parent=ConstantTablesEditor)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout.addWidget(self.add_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ConstantTablesEditor)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ConstantTablesEditor)
        self.tab_widget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(ConstantTablesEditor.accept) # type: ignore
        self.buttonBox.rejected.connect(ConstantTablesEditor.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ConstantTablesEditor)

    def retranslateUi(self, ConstantTablesEditor):
        _translate = QtCore.QCoreApplication.translate
        ConstantTablesEditor.setWindowTitle(_translate("ConstantTablesEditor", "Edit constant tables..."))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab), _translate("ConstantTablesEditor", "Tab 1"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_2), _translate("ConstantTablesEditor", "Tab 2"))
        self.add_button.setText(_translate("ConstantTablesEditor", "Add table..."))
