# Form implementation generated from reading ui file '.\create_parameters_viewer.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_ParametersDialog(object):
    def setupUi(self, ParametersDialog):
        ParametersDialog.setObjectName("ParametersDialog")
        ParametersDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(ParametersDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.titleLabel = QtWidgets.QLabel(parent=ParametersDialog)
        self.titleLabel.setObjectName("titleLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.titleLabel)
        self._window_title = QtWidgets.QLineEdit(parent=ParametersDialog)
        self._window_title.setObjectName("_window_title")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self._window_title)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ParametersDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ParametersDialog)
        self.buttonBox.accepted.connect(ParametersDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ParametersDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ParametersDialog)

    def retranslateUi(self, ParametersDialog):
        _translate = QtCore.QCoreApplication.translate
        ParametersDialog.setWindowTitle(_translate("ParametersDialog", "Dialog"))
        self.titleLabel.setText(_translate("ParametersDialog", "Title"))
