# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1179, 559)
        self._central_widget = QtWidgets.QWidget(parent=MainWindow)
        self._central_widget.setObjectName("_central_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self._central_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        MainWindow.setCentralWidget(self._central_widget)
        self._status_bar = QtWidgets.QStatusBar(parent=MainWindow)
        self._status_bar.setObjectName("_status_bar")
        MainWindow.setStatusBar(self._status_bar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GraphPlot"))
