# Form implementation generated from reading ui file '.\graphplot\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1179, 559)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self._sequences_dock = QtWidgets.QDockWidget(parent=MainWindow)
        self._sequences_dock.setFeatures(QtWidgets.QDockWidget.DockWidgetFeature.NoDockWidgetFeatures)
        self._sequences_dock.setAllowedAreas(QtCore.Qt.DockWidgetArea.LeftDockWidgetArea|QtCore.Qt.DockWidgetArea.RightDockWidgetArea|QtCore.Qt.DockWidgetArea.TopDockWidgetArea)
        self._sequences_dock.setObjectName("_sequences_dock")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self._sequences_dock.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self._sequences_dock)
        self._toolbox_dock = QtWidgets.QDockWidget(parent=MainWindow)
        self._toolbox_dock.setFeatures(QtWidgets.QDockWidget.DockWidgetFeature.NoDockWidgetFeatures)
        self._toolbox_dock.setAllowedAreas(QtCore.Qt.DockWidgetArea.RightDockWidgetArea)
        self._toolbox_dock.setObjectName("_toolbox_dock")
        self.dockWidgetContents_22 = QtWidgets.QWidget()
        self.dockWidgetContents_22.setObjectName("dockWidgetContents_22")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents_22)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self._tool_box = QtWidgets.QToolBox(parent=self.dockWidgetContents_22)
        self._tool_box.setObjectName("_tool_box")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 69, 495))
        self.page.setObjectName("page")
        self._tool_box.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 69, 483))
        self.page_2.setObjectName("page_2")
        self._tool_box.addItem(self.page_2, "")
        self.verticalLayout.addWidget(self._tool_box)
        self._toolbox_dock.setWidget(self.dockWidgetContents_22)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self._toolbox_dock)

        self.retranslateUi(MainWindow)
        self._tool_box.setCurrentIndex(0)
        self._tool_box.layout().setSpacing(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GraphPlot"))
        self._sequences_dock.setWindowTitle(_translate("MainWindow", "Sequences"))
        self._tool_box.setItemText(self._tool_box.indexOf(self.page), _translate("MainWindow", "Page 1"))
        self._tool_box.setItemText(self._tool_box.indexOf(self.page_2), _translate("MainWindow", "Page 2"))
