# Form implementation generated from reading ui file '.\graphplot\data_loader_selector.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_DataLoaderSelector(object):
    def setupUi(self, DataLoaderSelector):
        DataLoaderSelector.setObjectName("DataLoaderSelector")
        DataLoaderSelector.resize(400, 300)
        DataLoaderSelector.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.verticalLayout = QtWidgets.QVBoxLayout(DataLoaderSelector)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.dataLoaderLabel = QtWidgets.QLabel(parent=DataLoaderSelector)
        self.dataLoaderLabel.setObjectName("dataLoaderLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.dataLoaderLabel)
        self._data_loader_combo_box = QtWidgets.QComboBox(parent=DataLoaderSelector)
        self._data_loader_combo_box.setObjectName("_data_loader_combo_box")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self._data_loader_combo_box)
        self.verticalLayout.addLayout(self.formLayout)
        self._apply_button = QtWidgets.QPushButton(parent=DataLoaderSelector)
        self._apply_button.setObjectName("_apply_button")
        self.verticalLayout.addWidget(self._apply_button)

        self.retranslateUi(DataLoaderSelector)
        QtCore.QMetaObject.connectSlotsByName(DataLoaderSelector)

    def retranslateUi(self, DataLoaderSelector):
        _translate = QtCore.QCoreApplication.translate
        DataLoaderSelector.setWindowTitle(_translate("DataLoaderSelector", "Form"))
        self.dataLoaderLabel.setText(_translate("DataLoaderSelector", "Data loader"))
        self._apply_button.setText(_translate("DataLoaderSelector", "Apply"))
