# Form implementation generated from reading ui file '.\graphplot\watchlist_widget.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_WatchlistWidget(object):
    def setupUi(self, WatchlistWidget):
        WatchlistWidget.setObjectName("WatchlistWidget")
        WatchlistWidget.resize(400, 264)
        self.verticalLayout = QtWidgets.QVBoxLayout(WatchlistWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self._list_view = QtWidgets.QListView(parent=WatchlistWidget)
        self._list_view.setObjectName("_list_view")
        self.verticalLayout.addWidget(self._list_view)

        self.retranslateUi(WatchlistWidget)
        QtCore.QMetaObject.connectSlotsByName(WatchlistWidget)

    def retranslateUi(self, WatchlistWidget):
        _translate = QtCore.QCoreApplication.translate
        WatchlistWidget.setWindowTitle(_translate("WatchlistWidget", "Form"))
