# Form implementation generated from reading ui file '.\add_image_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_ImageDialog(object):
    def setupUi(self, ImageDialog):
        ImageDialog.setObjectName("ImageDialog")
        ImageDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(ImageDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.titleLabel = QtWidgets.QLabel(parent=ImageDialog)
        self.titleLabel.setObjectName("titleLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.titleLabel)
        self._window_title = QtWidgets.QLineEdit(parent=ImageDialog)
        self._window_title.setObjectName("_window_title")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self._window_title)
        self.cameraLabel = QtWidgets.QLabel(parent=ImageDialog)
        self.cameraLabel.setObjectName("cameraLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.cameraLabel)
        self._camera_line_edit = QtWidgets.QLineEdit(parent=ImageDialog)
        self._camera_line_edit.setObjectName("_camera_line_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self._camera_line_edit)
        self.pictureLabel = QtWidgets.QLabel(parent=ImageDialog)
        self.pictureLabel.setObjectName("pictureLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.pictureLabel)
        self._picture_line_edit = QtWidgets.QLineEdit(parent=ImageDialog)
        self._picture_line_edit.setObjectName("_picture_line_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self._picture_line_edit)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ImageDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ImageDialog)
        self.buttonBox.accepted.connect(ImageDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ImageDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ImageDialog)

    def retranslateUi(self, ImageDialog):
        _translate = QtCore.QCoreApplication.translate
        ImageDialog.setWindowTitle(_translate("ImageDialog", "Dialog"))
        self.titleLabel.setText(_translate("ImageDialog", "Title"))
        self.cameraLabel.setText(_translate("ImageDialog", "Camera"))
        self.pictureLabel.setText(_translate("ImageDialog", "Picture"))
