# Form implementation generated from reading ui file '.\configuration_editor.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TweezerArrangerConfigEditor(object):
    def setupUi(self, TweezerArrangerConfigEditor):
        TweezerArrangerConfigEditor.setObjectName("TweezerArrangerConfigEditor")
        TweezerArrangerConfigEditor.resize(400, 300)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(TweezerArrangerConfigEditor)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self._layout = QtWidgets.QHBoxLayout()
        self._layout.setObjectName("_layout")
        self.list_view = QtWidgets.QListView(parent=TweezerArrangerConfigEditor)
        self.list_view.setObjectName("list_view")
        self._layout.addWidget(self.list_view)
        self.horizontalLayout_2.addLayout(self._layout)

        self.retranslateUi(TweezerArrangerConfigEditor)
        QtCore.QMetaObject.connectSlotsByName(TweezerArrangerConfigEditor)

    def retranslateUi(self, TweezerArrangerConfigEditor):
        _translate = QtCore.QCoreApplication.translate
        TweezerArrangerConfigEditor.setWindowTitle(_translate("TweezerArrangerConfigEditor", "Form"))
