# Form implementation generated from reading ui file '.\image_view_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ImageViewDialog(object):
    def setupUi(self, ImageViewDialog):
        ImageViewDialog.setObjectName("ImageViewDialog")
        ImageViewDialog.resize(400, 300)
        ImageViewDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(ImageViewDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.viewNameLabel = QtWidgets.QLabel(parent=ImageViewDialog)
        self.viewNameLabel.setObjectName("viewNameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.viewNameLabel)
        self.view_name_line_edit = QtWidgets.QLineEdit(parent=ImageViewDialog)
        self.view_name_line_edit.setObjectName("view_name_line_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.view_name_line_edit)
        self.cameraNameLabel = QtWidgets.QLabel(parent=ImageViewDialog)
        self.cameraNameLabel.setObjectName("cameraNameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.cameraNameLabel)
        self.camera_name_line_edit = QtWidgets.QLineEdit(parent=ImageViewDialog)
        self.camera_name_line_edit.setObjectName("camera_name_line_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.camera_name_line_edit)
        self.imageLabel = QtWidgets.QLabel(parent=ImageViewDialog)
        self.imageLabel.setObjectName("imageLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.imageLabel)
        self.image_line_edit = QtWidgets.QLineEdit(parent=ImageViewDialog)
        self.image_line_edit.setObjectName("image_line_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.image_line_edit)
        self.backgroundLabel = QtWidgets.QLabel(parent=ImageViewDialog)
        self.backgroundLabel.setObjectName("backgroundLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.backgroundLabel)
        self.background_line_edit = QtWidgets.QLineEdit(parent=ImageViewDialog)
        self.background_line_edit.setObjectName("background_line_edit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.background_line_edit)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ImageViewDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ImageViewDialog)
        self.buttonBox.accepted.connect(ImageViewDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ImageViewDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ImageViewDialog)

    def retranslateUi(self, ImageViewDialog):
        _translate = QtCore.QCoreApplication.translate
        ImageViewDialog.setWindowTitle(_translate("ImageViewDialog", "Create image view..."))
        self.viewNameLabel.setText(_translate("ImageViewDialog", "View name"))
        self.cameraNameLabel.setText(_translate("ImageViewDialog", "Camera"))
        self.imageLabel.setText(_translate("ImageViewDialog", "Image"))
        self.backgroundLabel.setText(_translate("ImageViewDialog", "Background"))
        self.background_line_edit.setPlaceholderText(_translate("ImageViewDialog", "None"))
