"""Add device server to default device configurations table

Revision ID: 3b798541a770
Revises: babf96303363
Create Date: 2025-01-05 10:35:33.243123

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3b798541a770"
down_revision: Union[str, None] = "babf96303363"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "default_device_configurations",
        sa.Column("device_server", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("Downgrade is not supported")
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('default_device_configurations', 'device_server')
    # ### end Alembic commands ###
