"""Add data schema

Revision ID: dca55c13283b
Revises: 389b8e8b781e
Create Date: 2025-01-06 20:57:35.218727

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dca55c13283b"
down_revision: Union[str, None] = "389b8e8b781e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_schema",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_configuration_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("data_type", sa.JSON(), nullable=False),
        sa.Column("retention_policy", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_configuration_id"], ["device_config.id_"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_configuration_id", "label"),
    )
    op.create_index(
        op.f("ix_data_schema_device_configuration_id"),
        "data_schema",
        ["device_configuration_id"],
        unique=False,
    )
    op.create_table(
        "data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shot_id", sa.Integer(), nullable=False),
        sa.Column("schema_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.ForeignKeyConstraint(["schema_id"], ["data_schema.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["shot_id"], ["shots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("shot_id", "schema_id"),
    )
    op.create_index(op.f("ix_data_schema_id"), "data", ["schema_id"], unique=False)
    op.create_index(op.f("ix_data_shot_id"), "data", ["shot_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("Downgrade is not implemented.")
    # op.drop_index(op.f('ix_data_shot_id'), table_name='data')
    # op.drop_index(op.f('ix_data_schema_id'), table_name='data')
    # op.drop_table('data')
    # op.drop_index(op.f('ix_data_schema_device_configuration_id'), table_name='data_schema')
    # op.drop_table('data_schema')
