# Form implementation generated from reading ui file '.\exception_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ExceptionDialog(object):
    def setupUi(self, ExceptionDialog):
        ExceptionDialog.setObjectName("ExceptionDialog")
        ExceptionDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(ExceptionDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.exception_label = QtWidgets.QLabel(parent=ExceptionDialog)
        self.exception_label.setObjectName("exception_label")
        self.verticalLayout.addWidget(self.exception_label)
        self.line = QtWidgets.QFrame(parent=ExceptionDialog)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.exception_tree = QtWidgets.QTreeWidget(parent=ExceptionDialog)
        self.exception_tree.setHeaderHidden(True)
        self.exception_tree.setObjectName("exception_tree")
        self.exception_tree.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.exception_tree)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ExceptionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ExceptionDialog)
        self.buttonBox.accepted.connect(ExceptionDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ExceptionDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ExceptionDialog)

    def retranslateUi(self, ExceptionDialog):
        _translate = QtCore.QCoreApplication.translate
        ExceptionDialog.setWindowTitle(_translate("ExceptionDialog", "Dialog"))
        self.exception_label.setText(_translate("ExceptionDialog", "An error occured"))
