# Form implementation generated from reading ui file '.\atom_detector\configuration_editor\configuration_editor.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AtomDetectorConfigEditor(object):
    def setupUi(self, AtomDetectorConfigEditor):
        AtomDetectorConfigEditor.setObjectName("AtomDetectorConfigEditor")
        AtomDetectorConfigEditor.resize(400, 300)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(AtomDetectorConfigEditor)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.list_view = QtWidgets.QListView(parent=AtomDetectorConfigEditor)
        self.list_view.setObjectName("list_view")
        self.horizontalLayout.addWidget(self.list_view)
        self.frame = QtWidgets.QFrame(parent=AtomDetectorConfigEditor)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout.addWidget(self.frame)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(AtomDetectorConfigEditor)
        QtCore.QMetaObject.connectSlotsByName(AtomDetectorConfigEditor)

    def retranslateUi(self, AtomDetectorConfigEditor):
        _translate = QtCore.QCoreApplication.translate
        AtomDetectorConfigEditor.setWindowTitle(_translate("AtomDetectorConfigEditor", "Form"))
