# Form implementation generated from reading ui file '.\create_atom_viewer.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_AtomDialog(object):
    def setupUi(self, AtomDialog):
        AtomDialog.setObjectName("AtomDialog")
        AtomDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(AtomDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.titleLabel = QtWidgets.QLabel(parent=AtomDialog)
        self.titleLabel.setObjectName("titleLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.titleLabel)
        self._window_title = QtWidgets.QLineEdit(parent=AtomDialog)
        self._window_title.setObjectName("_window_title")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self._window_title)
        self.cameraLabel = QtWidgets.QLabel(parent=AtomDialog)
        self.cameraLabel.setObjectName("cameraLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.cameraLabel)
        self._detector_line_edit = QtWidgets.QLineEdit(parent=AtomDialog)
        self._detector_line_edit.setObjectName("_detector_line_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self._detector_line_edit)
        self.pictureLabel = QtWidgets.QLabel(parent=AtomDialog)
        self.pictureLabel.setObjectName("pictureLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.pictureLabel)
        self._picture_line_edit = QtWidgets.QLineEdit(parent=AtomDialog)
        self._picture_line_edit.setObjectName("_picture_line_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self._picture_line_edit)
        self.axesEqualLabel = QtWidgets.QLabel(parent=AtomDialog)
        self.axesEqualLabel.setObjectName("axesEqualLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.axesEqualLabel)
        self.axesEqualCheckBox = QtWidgets.QCheckBox(parent=AtomDialog)
        self.axesEqualCheckBox.setChecked(True)
        self.axesEqualCheckBox.setObjectName("axesEqualCheckBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.axesEqualCheckBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AtomDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AtomDialog)
        self.buttonBox.accepted.connect(AtomDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(AtomDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AtomDialog)

    def retranslateUi(self, AtomDialog):
        _translate = QtCore.QCoreApplication.translate
        AtomDialog.setWindowTitle(_translate("AtomDialog", "Dialog"))
        self.titleLabel.setText(_translate("AtomDialog", "Title"))
        self.cameraLabel.setText(_translate("AtomDialog", "Detector"))
        self.pictureLabel.setText(_translate("AtomDialog", "Picture"))
        self.axesEqualLabel.setText(_translate("AtomDialog", "Axes equal"))
